# Generated by Django 5.2 on 2025-05-10 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ida_app', '0002_events_usernotifications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usernotifications',
            old_name='event_id',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='usernotifications',
            old_name='user_id',
            new_name='user',
        ),
    ]
