# Generated by Django 5.2 on 2025-05-10 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ida_app', '0003_rename_event_id_usernotifications_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('announcements', models.BooleanField(default=True)),
                ('updates', models.BooleanField(default=True)),
                ('merch', models.BooleanField(default=True)),
                ('status', models.BooleanField(default=True)),
                ('reminders', models.TimeField(null=True)),
            ],
        ),
    ]
