# Generated by Django 5.2 on 2025-05-10 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ida_app', '0004_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='essential',
            field=models.BooleanField(default=False),
        ),
    ]
