# Generated by Django 5.2 on 2025-05-10 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ida_app', '0005_events_essential'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='body',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
