# Generated by Django 5.2 on 2025-05-10 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ida_app', '0006_events_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='image',
            field=models.TextField(default='https://i.imgur.com/Mw85Kfp.png'),
        ),
    ]
