# Generated by Django 5.2 on 2025-05-13 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ida_app', '0007_alter_events_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercredentials',
            old_name='is_staff',
            new_name='admin',
        ),
    ]
