# Generated by Django 5.2 on 2025-05-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ida_app', '0008_rename_is_staff_usercredentials_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='reminders',
            field=models.TextField(choices=[('off', 'Off'), ('30', '30 minutes before'), ('2', '2 hours before'), ('6', '6 hours before')], default='off'),
        ),
    ]
